# Generated by Django 5.0.1 on 2024-01-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=500, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('preference', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('material', models.CharField(max_length=300, null=True)),
                ('dimension', models.CharField(max_length=300, null=True)),
                ('colour', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('features', models.CharField(max_length=500, null=True)),
                ('desc', models.CharField(max_length=1000, null=True)),
                ('price', models.FloatField(null=True)),
                ('time', models.TimeField(auto_now=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('stock', models.IntegerField(null=True)),
                ('img1', models.ImageField(null=True, upload_to='media')),
                ('img2', models.ImageField(null=True, upload_to='media')),
                ('img3', models.ImageField(null=True, upload_to='media')),
                ('img4', models.ImageField(null=True, upload_to='media')),
                ('img5', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
