# Generated by Django 5.0.1 on 2024-01-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='finishtype',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
