# Generated by Django 5.0.1 on 2024-01-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0002_product_finishtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
