# Generated by Django 5.0.1 on 2024-01-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0003_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer1', models.ImageField(null=True, upload_to='offer')),
                ('offer2', models.ImageField(null=True, upload_to='offer')),
                ('offer3', models.ImageField(null=True, upload_to='offer')),
                ('offer4', models.ImageField(null=True, upload_to='offer')),
                ('offer5', models.ImageField(null=True, upload_to='offer')),
            ],
        ),
    ]
