# Generated by Django 5.0.1 on 2024-02-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0008_save_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.BigIntegerField(null=True)),
                ('shopaddress', models.CharField(max_length=300, null=True)),
                ('branddesc', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
