# Generated by Django 5.0.1 on 2024-02-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0009_registerationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerationrequest',
            name='Status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
