# Generated by Django 5.0.1 on 2024-02-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0012_sellerdetails_contact_sellerdetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerdetails',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='sellerdetails',
            name='email',
        ),
    ]
