# Generated by Django 5.0.1 on 2024-02-09 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0013_remove_sellerdetails_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdetails',
            name='sellerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='furnapp.registerationrequest'),
        ),
    ]
