# Generated by Django 5.0.1 on 2024-02-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0014_alter_sellerdetails_sellerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerdetails',
            old_name='sellerid',
            new_name='seller',
        ),
    ]
