# Generated by Django 5.0.1 on 2024-02-09 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0016_product_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetails',
            name='bname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerdetails',
            name='branddesc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sellerdetails',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sellerdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sellerdetails',
            name='shopaddress',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
