# Generated by Django 5.0.1 on 2024-02-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0017_sellerdetails_bname_sellerdetails_branddesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdetails',
            name='brandlogo',
            field=models.ImageField(null=True, upload_to='media/brandlogo'),
        ),
    ]
