# Generated by Django 5.0.1 on 2024-02-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0018_alter_sellerdetails_brandlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdetails',
            name='brandlogo',
            field=models.ImageField(null=True, upload_to='brandlogo'),
        ),
    ]
