# Generated by Django 5.0.1 on 2024-02-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0020_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Aea',
            new_name='area',
        ),
    ]
