# Generated by Django 5.0.1 on 2024-02-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0024_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
