# Generated by Django 5.0.1 on 2024-02-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0025_userdetails_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='Gender',
        ),
    ]
